# Generated by Django 5.1.2 on 2024-10-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_imagengeneralversiondos'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('tipo', models.CharField(choices=[('ai', 'IA'), ('human', 'Humano')], max_length=10)),
            ],
        ),
    ]
